### ISSUE TITLE
System Out of memory exception was thrown

### ISSUE THREAD

**Issue by jimi202008** [wabbajack-tools/wabbajack#1131]
![dsds](https://user-images.githubusercontent.com/73021682/96335586-52880f80-10ac-11eb-9570-21380f332db1.png)

Every time I run to 3DNPC.bsa, it will report an error. I used to install a lower version of wabbajack to avoid it, but now the new version does not work.
Does anyone know how to avoid this?

**Comment by Joerger** [comment]
So this isn't really a bug, you just need to configure your pagefile. I would recommend they add a better error message since it happens frequently enough. Also I'd suggest checking the wabbajack discord and ask for help before posting an issue here.

------ Discord Help----------

Page files and memory crashes
Bigger Skyrim modlists need a lot of memory, and when there is not enough available it may fail allocating more. To fix this, you'll want to have a bigger pagefile.

A pagefile is a file on your disk Windows will use when there is not enough RAM available.

Never disable the pagefile - this may lead to various issues on your system, such as this Skyrim crash.

If you've never touched the pagefile, try performing the following steps:
1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.

**Comment by tr4wzified** [comment]
Not a bug - should be closed
