### ISSUE TITLE
Vortex Support

### ISSUE THREAD

**Issue by pmutch** [wabbajack-tools/wabbajack#1389]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when my favorite tools don't work together. 

Vortex was easy to install and easy to use, and has made modding Skyrim a breeze. Unfortunately, it's not compatible with Wabbajack, which means I can't share my setup with the world. 

**Describe the solution you'd like**

I know Vortex and MO2 are completely different tools, but I would LOVE to be able to use Wabbajack without having to start from scratch, and I know there have to be thousands of other users who feel the same way.  If Wabbajack supported creating modlists from Vortex, it would create an even better modding experience for many, many users, and would expand Wabbajack's user base even further beyond what it already is. 

**Describe alternatives you've considered**

I've considered installing MO2. I may yet have to do that, but I'm not looking forward to it. 

**Additional context**

Thank you for everything you've done to contribute to the Skyrim community, and I look forward to seeing Wabbajack continue to grow!

**Comment by erri120** [comment]
I implemented Vortex support back in 2019 (#142) and we removed it in April 2020 (#699) mainly because no one was really using it and the code was hard to maintain.

We will probably never re-add this feature because there is still little to no interest and maintaing it would be rather painful because all Wabbajack devs use MO2 and it won't be well tested.
