### ISSUE TITLE
LL Login Whitescreen error fix

### ISSUE THREAD

**Issue by canefe** [wabbajack-tools/wabbajack#1618]
### **Describe the bug**

![](https://media.discordapp.net/attachments/666599178788536331/891372204296634448/unknown.png)
#1523 ( maybe )

### **How I fixed it**
Win 10. I updated my windows to 21H1 as discord mods suggested that to fix the problem but that didn't solve the white screen error. Then I checked the [source](https://github.com/wabbajack-tools/wabbajack/blob/2b1e0f73cf59a116decc41df8f0edba2d465c882/Wabbajack.Lib/Downloaders/LoversLabOAuthDownloader.cs). From browser, I can't open https://loverslab.com/ but I can open https://www.loverslab.com/ . So I tried changing [this line of code](https://github.com/wabbajack-tools/wabbajack/blob/2b1e0f73cf59a116decc41df8f0edba2d465c882/Wabbajack.Lib/Downloaders/LoversLabOAuthDownloader.cs#L17) (and line 22, 23).

And It worked. White screen gone, I was able to log in and stuff.

### **Wabbajack Version**
Latest

**Comment by EzioTheDeadPoet** [comment]
you could send this as a pull request if you didn't already.

**Comment by RfHardian** [comment]
Thank you very much! It's working!

**Comment by JustsomeGuydoingguystuff** [comment]
Hello Canefe, how can I open this source?
When I do a right click and click on view page source it's open the editor, but I can't find those lines.
could you or anyone show me how to find it in easy English please?

**Comment by SaltSouls** [comment]
Yeah, version 2.5.3.9 is still completely broken when it comes to LL.
Keeps giving me this error.
`104.38 - Got a 503 from https://loverslab.com/oauth/token/ retrying in 488ms`
Don't know what the above proposed fix is or how to get it working, but would love some help if this issue is supposedly already resolved.

**Comment by EzioTheDeadPoet** [comment]
Linux isn't officially supported, so besides trying to use the latest windows in your wine settings I can't offer much more.

There is some work put into the big 3.0  that might allow WJ to work with a command line interface and without a GUI in Linux but that update is still not ready. And even then it is still functionality wise hard to get it to properly install lists if the games are practically in their own sandboxes.

**Comment by SaltSouls** [comment]
> 

Ummm... No one here was using Linux. OP is on Windows 10, and like I said, I'm on Windows 11.

**Comment by EzioTheDeadPoet** [comment]
Then the list you are installing hasn't updated to use the manual installer over the old now broken API implementation. just have patience or try licentia or tsukiro those two are updated or already have updated versions ready that will soon release.

**Comment by SaltSouls** [comment]
Okay, A little confused at what you are getting at here. The issue isn't with the list/operating system. It is with the code for Wabbajack being faulty when it comes to LoversLab, hence the urls missing the `www.` portions of the url. The OP posted the fix for this above, but it wasn't added to the latest version. Hence it still being broken, not an Issue with LoversLab, just the code.

Now, if your are trying to tell me that support for downloading Loverslab files is going to be axed, then that's a whole different issue altogether. Though not relevant to the current bug report.

**Comment by EzioTheDeadPoet** [comment]
The issue is the IT department of LL that messed up their API. 

The links Wabbajack uses are provided by that. 

We fixed that in the latest version by changing how we source files from LL by making WJ show you the LL page and having people trigger the download manually, but lists need to update with a new compile if they hadn't set the files up to use that manual downloader during installation.

So you can wait for the lists to update or cling on whichever list you are trying to install and pray that LL gets their stuff together.
