### ISSUE TITLE
Unable to reach Vector Plexus stops all downloads

### ISSUE THREAD

**Issue by jahrends** [wabbajack-tools/wabbajack#1963]
Why can't I disable or tell the code not to use Vector Plexus.  It is down and I start to do a pull and it stops EVERYTHING to prompt for a login to Vector instead of pulling the parts that it can actually pull from Nexus?

**Comment by Lartza** [comment]
That's unfortunately currently how it works. You can manually download the failing mods when that is an option, but otherwise WJ would need to change to let you DOWNLOAD everything else while you wait. Installing would still not be possible

**Comment by Dragnier** [comment]
https://github.com/cacophony-wj/LeS/issues/59#issuecomment-1153011389

As stated in the above modpack issue comment, there is a temporary, if occasionally down, backup of the vectorplexus.com website at [https://vectorplexus.sh1ny.net/](https://vectorplexus.sh1ny.net/). It might be nice to add an option checkbox that allows redirecting Wabbajack to use that instead of the original which probably isn't coming back.

**Comment by im-mortal** [comment]
I might add `https://vectorplexus.sh1ny.net` shouldn't be considered a backup but a mirror, even if temporary. If and when another domain name change takes place, it will point to the new location with a 301 redirect.

**Comment by catchra** [comment]
vector plexus has a new domain now at https://vectorplexis.com/
it looks like they lost the old one

**Comment by im-mortal** [comment]
It is another mirror domain that's significantly easier to access, compared to `vectorplexus.sh1ny.net`. `vectorplexus.com` hasn't gone to auction yet.

**Comment by makoto-kokoroki** [comment]
is there no way to simply change the 'vectorplexus' login data in some configuration file by oneself to the mirror domains?
