### ISSUE TITLE
VectorPlex(u)s is now VectorPlex(i)s

### ISSUE THREAD

**Issue by JehanRock** [wabbajack-tools/wabbajack#2008]
So VectorPlexus is now VectorPlexis and I guess all the Login systems and links either:

A. Gets/Request any mod list to be updated to the new Link of https://vectorplexis.com/ (The "i" in Plexis was formerly Plexus to those not aware)

B. Add in a Script that redirects any and all VectorPlexus(old) links into the new where it simply replaces the link before the file. I guess example would look like this:

 https://vectorplexus.com/files/file/283-high-poly-head/ -> https://vectorplexis.com/files/file/283-high-poly-head/
 
 Note: Apologies ahead of time if this issue is already there and planned. I rarely use GitHub and decided to check since Wabbajack is having issues in creating said account for VP but could not find an Issue regarding the fact that VectorPlexus has now been changed to VectorPlex*_i_*s.

**Comment by EzioTheDeadPoet** [comment]
the only mod that really was sourced from the site now has an official gdrive mirror by the author (High Poly Head). 
which is more reliable and doesn't require logins. So VP might be scratched in the future. Especially since we had frequent enough issues with people being unable to login and more via the official api. additionally as far as I understand it that name change isn't intended to stay that way forever either.
