### ISSUE TITLE
LoversLab sign in white screen of death

### ISSUE THREAD

**Issue by QuirkySheDevil** [wabbajack-tools/wabbajack#2019]
Hi guys,
Sorry for bothering you but I was prompted to relog into LoversLab when downloading a new modlist (masterstroke). When I tried I got stuck on the sign in page which never loads. Just a permanent white screen. I googled and know this has happened before, but the fixes I read about are beyond my skills. Normally, I would try but I was so confused trying to just read it I'm not brave enough to try to fix it on my own. 
Love your guys work,
QuirkySheDevil

**Comment by Bunungo** [comment]
Wanted to mention that I'm also having the same issue. And pretty much everyone trying to install the masterstroke pack or others using loverslab's API. 

I should note that Tahrovin for Skyrim VR has circumvented the issue by linking to the loverslab page for each mod and asking the user to download the file from that page manually rather than using the API and seems to work fine. But it would be nice to have automated installs for LL back.
