### ISSUE TITLE
Wabbajack Ui is Messed up.

### ISSUE THREAD

**Issue by ThorDragonMk** [wabbajack-tools/wabbajack#2070]
**Describe the bug**
Wabbajack window size doesn't work as it should.

Keeps trying to resize the window and the cursor is way above where it actually is on the screen.

Options become grey and untextured when i hover over them aswell.

Not sure how to be more specific without showing it, I only have this problem with wabbajack.

**Additional Context**
Win 11. SSE.

**Wabbajack Version**
Wabbajack v2.5.3.28

**Logs**

[Wabbajack 2022-09-07 15_59_12.log](https://github.com/wabbajack-tools/wabbajack/files/9507052/Wabbajack.2022-09-07.15_59_12.log)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9507054/Wabbajack.current.log)

**Images**
Messed up UI.
![Glitched Ui](https://user-images.githubusercontent.com/106917717/188906920-a4ee598b-17b0-4ad4-af54-29f06d436da3.png)
Mouse is below login, on manual mod downloads aswell, as stated above.
![Screenshot 2022-09-07 164758](https://user-images.githubusercontent.com/106917717/188908521-aece7d16-15aa-4b43-af4d-9055dd8c94c0.png)

**Comment by ykamal** [comment]
I am seeing a completely different UI. I am not sure if this is intentional. If so, it's not as pleasant an experience as before.

The settings section is missing:

![image](https://user-images.githubusercontent.com/50125998/192738288-d9ac4a97-e3e0-4eb3-85cf-ddbe1a22502c.png)

The gallery navigation is missing:

![image](https://user-images.githubusercontent.com/50125998/192738476-f557fb29-ed99-49c9-8c09-e2ffcc86d4eb.png)

**Comment by EzioTheDeadPoet** [comment]
> I am seeing a completely different UI. I am not sure if this is intentional. If so, it's not as pleasant an experience as before.
> 

this is expected and intended behavior. you can currently edit the settings be opening and editing the file

**Comment by EzioTheDeadPoet** [comment]
@ThorDragonMk The whole app had an update, please check if the issues still apply and make a new issue with details for any still present/new issues you find.
