### ISSUE TITLE
Wabbajack doesn't fully support network shares

### ISSUE THREAD

**Issue by Gerdofal** [wabbajack-tools/wabbajack#2157]
**Describe the bug**
Ref: https://github.com/wabbajack-tools/wabbajack/issues/2024

Still an issue in 3.0.3.1

Wabbajack doesn't like using network drives or shares. It tends to re-write them to be a folder on some drive (see above reference link). Also, in 3.0.3.1, it won't allow the root folder of a share, need to have a subfolder inside or WJ won't allow the selection

**Additional Context**

Windows 10 and 11

**Wabbajack Version**

WJ 3.0.3.1

**Comment by EzioTheDeadPoet** [comment]
Considering that Wabbajack is in maintenance mode for the most part adding a niche feature like network drive support is not on the list of improvements that are planned any time soon. So I will close this issue for now. Especially since none of the current devs would have a setup to test and debug such a niche issue.
