### ISSUE TITLE
Windows lacks a default app for opening .json files, becoming an issue when trying to change settings

### ISSUE THREAD

**Issue by Ameno-Sagiri** [wabbajack-tools/wabbajack#2202]
Windows doesn't have a default association for .json files.
![2022-11-10-18-07-17_cmd](https://user-images.githubusercontent.com/5976053/201231824-a879d014-e7fe-4c3e-aad1-f0f1d002485b.png)
>Edit: Removed the passive aggressive elements of this report, cause it actually made me not want to work on this or even talk with others about it.
>Luca

**Comment by EzioTheDeadPoet** [comment]
The reasons the settings are moved to a file are the following:
- Wabbajack needs to be restarted for applying them.
- You shouldn't need to change them in most cases and if you do it is a set it and forget it thing.

What can be improved is adding a fallback if no program is associated with JSON files to use the default MS Editor application. Which I would have expected to actually be used already as a fallback, which sparks the question did you remove the default Windows text editor in an effort to "debloat" Windows ? If so, then it is an issue that won't be fixed since you broke your OS.

**Comment by EzioTheDeadPoet** [comment]
[Microsoft Support Forum Post about it.](https://answers.microsoft.com/en-us/windows/forum/all/default-programs-and-file-association/62ee39f6-8aff-46bf-a68b-0b800b1b6c99)

@erri120 
Any idea if we could add a fallback, if association fails that it looks for the MS Notepad and if that fails it tells the user not to break their windows 🤣 ?

**Comment by EzioTheDeadPoet** [comment]
hasn't come up in a while, which to me implies that the creator of the issue either uninstalled the default windows text editor or used some custom windows ISO or "debloater" tool which caused the issue.

**Comment by portal-draakje** [comment]
![Schermafbeelding 2024-07-06 140141](https://github.com/wabbajack-tools/wabbajack/assets/69325629/8de1de0e-0f68-4b04-9500-cd03ad4a80a5)
i did try to open a .json file, and it opens notebook in default it knows i want to open. but i can only click a button that says open ones with. but i want to set it to default.

**Comment by EzioTheDeadPoet** [comment]
That's something YOU need to set in your windows settings.

Just right click a .json file and set the default via that menu in Windows.

This is not something WJ needs to do for you.

**Comment by portal-draakje** [comment]
but the button is not there...

**Comment by portal-draakje** [comment]
i did try by just dubble clicking and that also does not work... it's more annoying than the time windows did add a extra option in settings to turn on or off your pad from the laptop. and i did not find out it was false at default. so i did just think my pad was broken, until i did found the setting... after some weeks.

**Comment by EzioTheDeadPoet** [comment]
> but the button is not there...

https://www.google.com/search?q=how+to+set+app+for+file+type+windows+11
