### ISSUE TITLE
modlist.txt hash fail on list update

### ISSUE THREAD

**Issue by Styyx1** [wabbajack-tools/wabbajack#2204]
**Describe the bug**

Wabbajack does not delete the modlist.txt for the second profile in MO2 on updating the list. Instead it compares hashes and obviously fails due to a mismatch

**Additional Context**

I updated Krahven with a very minor fix that only changed 2 mods, if that's relevant. User had to delete the profile folder (modlist.txt is stored in there) in order to properly update the list. 

**Wabbajack Version**

3.0.4.0 although the log is from 3.0.3.1, but user insists in getting the same error after updating Wabbajack. 

**Logs**
Log is from WJ 3.0.3.1, sadly i did not get one from 3.0.4.0.

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/9996898/Wabbajack.current.log)

**Comment by chri3i** [comment]
now here's a log from the latest Wabbajack version. it does not fail on the same file, but I'm fairly sure that the issue is basically the same. It fails on the .compiler_settings file in this log

[Wabbajack.current2.log](https://github.com/wabbajack-tools/wabbajack/files/9996925/Wabbajack.current2.log)
