### ISSUE TITLE
Cannot Interact with Nexus Login Dialog

### ISSUE THREAD

**Issue by terminal-case** [wabbajack-tools/wabbajack#2212]
I'm trying to log into my Nexus account in the latest version of Wabbajack (3.0.4.1) and I cannot interact with any of the text input fields. I saw an old possible solution on reddit that involved updating my graphics driver, and also moving the window around after typing to see if it updated at that point, but neither of these things helped.

**Comment by EzioTheDeadPoet** [comment]
We need:

- Wabbajack logs
- operating system information
- PC specs 

to solve this issue, because we and most other people don't have the same issue with implies that it is caused by an interaction with your system worst case even some other application running in the background breaking Wabbajack (this would be even harder to debug).

**Comment by terminal-case** [comment]
Update: this seems to have been caused by a workaround I was using to avoid having to re-enable UAC. I really don't like having it on.

I was running Wabbajack by going into the version-number-named folder containing the executable and running the following:
`RUNAS /trustlevel:0x20000 wabbajack`

After re-enabling the lowest level of UAC, and subsequently being able to run the Wabbajack exe outside of the version-number folder, I was able to interact with the input fields and log in.
