### ISSUE TITLE
7z.exe: The system cannot find the file specified.

### ISSUE THREAD

**Issue by cacophony-wj** [wabbajack-tools/wabbajack#2218]
**Describe the bug**

Often at the end of the installation of a modlist, when extraction of the Wabbajack file is attempted, the process fails with an error regarding 7z.exe: "The system cannot find the file specified." Uninstalling antivirus and repeating the process does not result in any change of operation.

**Additional Context**

Windows 10, Version 21H2 (OS build 19044), Skyrim Special Edition

**Wabbajack Version**

3.0.4.1

**Logs**

[Wabbajack.current (1).log](https://github.com/wabbajack-tools/wabbajack/files/10071353/Wabbajack.current.1.log)

**Comment by Mieekaserra** [comment]
One of my users also had this

https://cdn.discordapp.com/attachments/881254575640838254/1044696345212112977/Wabbajack.current.log

User resolved by deleting the wabbajack file and redownloadng via the UI

**Comment by Dace617** [comment]
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10118453/Wabbajack.current.log)

This issue is most commonly caused for me (both personally and in a support sense) by opening a Wabbajack file directly (right click > open, double clicking the WJ file etc.) 99% of the time having them open Wabbajack itself and then using the Install from Disk option will solve the problem immediately.

**Comment by EzioTheDeadPoet** [comment]
@erri120 looks like file association still needs some work/fixes.

**Comment by Mieekaserra** [comment]
Not stale - Please reopen

**Comment by EzioTheDeadPoet** [comment]
still present

**Comment by EzioTheDeadPoet** [comment]
looking at it again it is the issue users can fix by redownloading the .wabbajack file right ? 
Because it it is the 7zip error at the end of the installation ?

**Comment by Mieekaserra** [comment]
Luca: this was the original report where if the user opened the wabbajack file directly they had the 7zip error. Redownloading it, or opening it Via the UI (load from files) had no issues.
