### ISSUE TITLE
Wabbajack File Corruption Mystery

### ISSUE THREAD

**Issue by cacophony-wj** [wabbajack-tools/wabbajack#2240]
**Describe the bug**

At times certain files become corrupt after Wabbajack installations that vary between compilation attempts. Many times these corruption issues are resolved by reinstalling the list with a current or previous version. Most recently I experienced physics crashes for a certain armor mesh that had been binary patched (the Vanguard armor from the Immersive Armors Fixes mod). After replacing the mesh from that mod with another version and rebuilding BodySlides for binary patching, I began to receive similar crashes for a different file, which appears to be related to an NPC head, that I did not experience previously.

**Additional Context**

These bug appear to occur more commonly for my list than other lists. It just dawned on me that the problem may not be my users' connections, but mine, or some combination of my connection and the users. I figured I would submit all logs from all of my compilation attempts to see if some error can be identified that may be causing the binary patching or some other process of Wabbajack compilation to foster file corruption.

**Wabbajack Version**

3.0.4.1, Windows 11, all current updates to system and drivers, Windows Defender and MalWareBytes with proper exclusions for all relevant folders

**Logs**

The logs are too large to submit via Github so I have compressed them all and posted them to MEGA. I have also included a handful of logs that appear to be from the installation side, but it appears most users delete Wabbajack including logs when troubleshooting and no longer have them to submit after they solve their problem. You can find all of these logs here:

https://mega.nz/folder/lHoThaqB#CNUyMepMJe1UZemJYUsbzg

**Comment by ForgottenGlory** [comment]
[Crash_2022_10_19_22-29-9.txt](https://github.com/wabbajack-tools/wabbajack/files/10461675/Crash_2022_10_19_22-29-9.txt)
[Crash_2022_12_14_12-9-14.txt](https://github.com/wabbajack-tools/wabbajack/files/10461676/Crash_2022_12_14_12-9-14.txt)
[Crash_2023_1_13_3-51-34.txt](https://github.com/wabbajack-tools/wabbajack/files/10461677/Crash_2023_1_13_3-51-34.txt)


Seems it can happen with any mesh, I don't believe there's a set pattern to it. 

A workaround for users is to delete the mesh in question (or the mod folder containing that mesh) and re-install the list with WJ. It isn't an issue on the person compiling the list's end as far as I can tell, but an issue with WJ installing the meshes. I'm unable to reproduce crashes that users submit due to this.

**Comment by cacophony-wj** [comment]
Added more logs to the MEGA link

**Comment by EzioTheDeadPoet** [comment]
still monitoring the issue to find the cause.

**Comment by EzioTheDeadPoet** [comment]
Update:

On the discord we made the observation, that it seems to be related to the MO2 profiles and some issues with either reading them correctly or installing them or all the mods correctly.

In what way or what exactly is happening is still kinda foggy but there is some progress on figuring out this issue.
