### ISSUE TITLE
Modlists in gallery of app and website cannot load lists

### ISSUE THREAD

**Issue by prashanthsn** [wabbajack-tools/wabbajack#2245]
**Describe the bug**

Modlists are not loading in the website or app version. I tried to connect to a VPN and it works, but can't download due to free VPN limits

**Additional Context**

OS (Win 11 22H2) and Game type (SSE)

**Wabbajack Version**

Wabbajack v3.0.4.1

**Logs**
![Screenshot (406)](https://user-images.githubusercontent.com/66014605/206893319-43b69457-acbf-40e8-a96d-202cdc20867c.png)
![Screenshot (403)](https://user-images.githubusercontent.com/66014605/206893321-a46def3e-063f-49fc-a397-4e83d8bd2c9f.png)
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10201711/Wabbajack.current.log)
[github troubleshoot.txt](https://github.com/wabbajack-tools/wabbajack/files/10201715/github.troubleshoot.txt)

**Comment by EzioTheDeadPoet** [comment]
This is an issue in YOUR network that blocks the API calls the Wabbajack and Website do to the config and meta data files hosted on GitHub. And it is weird that you can write an issue here on GitHub but again nothing we can do about it.

Check your OS, Home network and worst case even your ISP because the issues lies with one of those 3.

**Comment by EzioTheDeadPoet** [comment]
We are sadly unable to fix connectivity issues caused by your network.
