### ISSUE TITLE
Wabbajack File Overwrite Warning not Working

### ISSUE THREAD

**Issue by GeneralMole** [wabbajack-tools/wabbajack#2262]
**Describe the bug**

Updated a modlist, successful install, ran again (didn't check the overwrite box), it cleaned the mods folder and started exporting it all over again.

**Additional Context**

Win 10, SSE AE

**Wabbajack Version**

3.0.5.0

**Logs**

[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/10326955/Wabbajack.current.log)

**Comment by EzioTheDeadPoet** [comment]
Even if you don't check the overwrite box, you have a dialog that follows that tells you that it will do that. Checking the box just skips that warning.

**Comment by GravenImages** [comment]
For what it's worth, since 3.0+ I don't think I've ever seen that confirmation dialogue, though what OP is referring to is that they're rerunning WJ over an existing modlist install, and WJ is wiping the install clean and reextracting from downloads. I have also had this happen, though the logs were very unhelpful.

**Comment by GeneralMole** [comment]
This is still an issue in 3.0.6.2
