### ISSUE TITLE
Feature Request : Have Wabbajack make sure to support multiple versions of a game (Steam, GoG, Epic) natively.

### ISSUE THREAD

**Issue by TomTurbine** [wabbajack-tools/wabbajack#2375]
Noticed when I tried playing games on Skyrim SE and Fallout New Vegas that most of the modlists require the steam version because it wants to scan for files that aren't needed for the games like the redistribution files.

My suggestion is just for Wabbajack to only scan for what is needed and not something that is unique to a single version of the games, it really does lock out users who aren't using that specific version.

Mentioned it to one author and they said the scan was part of wabbajack itself to make sure you were using "A genuine steam copy" of the game which isn't the only genuine version and minus a few select mods (Like the script extender) they don't require a specific copy per instance at which point they could just include multiple copies in the load order in a "Choose One" section.

While Steam is the big one, many like myself enjoy the GoG versions as it allows us to control if and when we allow updates and we don't need a secondary client in the background just to play a single player game.

The mod author shouldn't really be forced to create situations where a singular client is all it boots on and the rest is excluded when the mods themselves have no  such limitation.

**Comment by EzioTheDeadPoet** [comment]
1. Many mods **DO** have limitations with store versions.
2. The literal binary files (.EXE/.DLL) are different in different stores and are mandatory to check.
3. There are already ways to tweak around that, but those depend on the people making the list.
4. WJ only scans for the files a list actually touches (copies and modifies), so it depends on list authors to account for different store versions of a game.
5. Even if we would love more authors to consider taking steps for making point 4. happen we sure as hell won't force anyone because:
  - This is a free time hobby project!
  - The amount of work required for a very small target audience would cause authors to just quit killing the project!
6. As explained above no author is forced to do anything. 
7. We also can't just patch every stores version to for example a unified DRM less GOG copy and use those as baselines for installations because doing so would strip the DRM from games and WE don't want the possible legal issues from that to kill the project.

**Comment by TomTurbine** [comment]
I know some mods do require specific versions but they also make multiple copies for them.

As far as Wabbajack only scanning files it touches, that means you have mods that are modifying directx redistributables which doesn't make any sense why they would touch them.

And I never mentioned forcing mod others to make mods for stuff they don't want, I was trying to stop forcing them to either abandon other systems or being forced to make multiple copies of the same load orders.

Didn't know that GoG and Epic were small niche game clients.

One thing that doesn't make sense to me though your #7. Wabbajack doesn't even modify the install folder for the game itself I thought, if it did, I definitely don't want to use it. So either Wabbajack is modifying my game files which is something I definitely don't want at all or it isn't at which point this isn't an issue.

If Wabbajack modifies the game file I can see the issues with the multi-system installers but also means I would rather not use this because I am trying to keep my games install folder untouched.

If Wabbajack doesn't modify the game folder and just mainly works like just a Mod Organizer 2 preconfigured, then which system ultimately doesn't matter given they have root builder and the few plugins and executables that do require specific systems they make versions for each of them.

**Comment by EzioTheDeadPoet** [comment]
7. WABBAJACK COPIES THE GAME FILES AND SOMETIMES EDITS THOSE COPIES

But for those edits to work it needs the correct versions of those files.

Please read our [WIKI](https://wiki.wabbajack.org/modlist_author_documentation/Compilation.html) on how to make lists before throwing further assumptions around.

**Comment by TomTurbine** [comment]
Ah, did not realize that, my apologizes.

No clue why some would copy directx redistributables but so be it. Thank you for your time and responses.
