### ISSUE TITLE
Dont run Wabbajack as Admin!

### ISSUE THREAD

**Issue by nizeyoral** [wabbajack-tools/wabbajack#2410]
Well as we already had a whole thread about this problem on Reddit, I just want to know why tf this App is the only app that I showing this Error since years? And why nobody is fixxing it? A reddit user modified this and removed the code and it works comepletely fine. So why its still in the original build?
I really dont need an additional user on my windows just because the dev is trashcoding here. I would understand if mutliple apps would need non admin accounts but this problem only exisits in Wabbajack.
FIX IT FINALLY.

Cheers

**Comment by EzioTheDeadPoet** [comment]
Fix your PC setup and re-enable UAC.
This is a Change made on purpose that will stay with the app. If you don't like it you can either fork this project and remove the check, because then you basically prove you are knowledgeable enough to not fuck up your PC when using WJ as an admin user. OR use other tools like Nexus Collections.

[Wiki Entry on the topic](https://wiki.wabbajack.org/user_documentation/Troubleshooting%20FAQ.html#dont-run-as-admin)

**Comment by nizeyoral** [comment]
Youre pathetic, you cant even explain this "feature" because you prob trashcoding everything here and if other users fix this nonsense feature, then you frame them as "not enough knowledgeable". You cant even explain this on your wiki you little idiot.
#trashcoder
