### ISSUE TITLE
Won't Open

### ISSUE THREAD

**Issue by SmashingMist27** [wabbajack-tools/wabbajack#2498]
**Starts to launch then fails**

Nothing on the internet will help me 

Win 10, want to use on sse but cant open to begin with

**Version 3.5.0.1**

cant find any logs. dont have any or just dont know where to look.

**Comment by tr4wzified** [comment]
We need more information to be able to act on this. Wabbajack logs are in the logs subdirectory (inside the version folder). Would also appreciate an Event Viewer log, we can't do anything with this little information.

**Comment by 2KDrop** [comment]
Not the original guy but same issue, here's the log that comes up personally
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/14235194/Wabbajack.current.log)
This happens both when launching from the specific Wabbajack version and when launching from the exe that downloads the newest version

**Comment by Mieekaserra** [comment]
i think you are banned....


been trying to install one of hitmanb's lists using an old wabbajack version?

**Comment by SmashingMist27** [comment]
after leaving it alone for a while i tried installing again, it opened this time and i even downloaded a modpack kinda. now having a problem where every mod downloaded is a zip and there’s never seperate folders or a mo2exe

**Comment by SmashingMist27** [comment]
dont know how i accidentally closed the issue lol

**Comment by EzioTheDeadPoet** [comment]
> after leaving it alone for a while i tried installing again, it opened this time and i even downloaded a modpack kinda. now having a problem where every mod downloaded is a zip and there’s never seperate folders or a mo2exe

because the installation didn't finish or you opened the wrong folder. Considering the app started for you this issue can be closed now.

**Comment by 2KDrop** [comment]
Hey sorry to bring this back up but thought I'd just comment on this again instead of opening another that would be redundant but I still cannot open Wabbajack without it immediately crashing, here is a log from a _completely fresh_ download of 3.5.0.1
[Wabbajack.current.log](https://github.com/wabbajack-tools/wabbajack/files/14255214/Wabbajack.current.log)

It was also unable to find my copy of Skyrim before this but that may have just been from it being too up to date.
