### ISSUE TITLE
Moderator closed my report without giving information on how to fix just a " go to the support channels for the lists you are trying to install." 

### ISSUE THREAD

**Issue by lomo2302** [wabbajack-tools/wabbajack#2667]
where is the support channel? there is no guidance or walkthrough or links to help with these types of issues and its very unprofessional to close a ticket without providing proper support.

**Comment by Mieekaserra** [comment]
You were told its on the discord of whatever list you are trying to install. Go there. Look for support chanel.  Ask for help.

Wabbajack cannot help you with with broken downloads.

**Comment by lomo2302** [comment]
lmao it's your guy's fucking platform and you don't even do quality control now its confirmed how unprofessional you guys are lmao. Nexus's vortex might be slower but I've never had these stupid ass retarded problems like your pos program.

**Comment by EzioTheDeadPoet** [comment]
> where is the support channel? there is no guidance or walkthrough or links to help with these types of issues and its very unprofessional to close a ticket without providing proper support.

The website gallery directly links you to the valid discord channels.
And the gallery links you to the READMEs/Documentation that is mandatory reading for installing lists and features the invite URL for the relevant support discord.

This is not an issue with the app.

This is effectively an off-topic issue.
Also this is not a paid service so that "not professional" statement falls flat on the account of you trying to get support at the wrong source and this not being a paid service with any premium support claims.

This is a passion project maintained by volunteers in their free time with 0 obligations to anyone.
