### ISSUE TITLE
Long Descriptions Get Cut Off

### ISSUE THREAD

**Issue by ForgottenGlory** [wabbajack-tools/wabbajack#783]
**Describe the bug**
Long descriptions on the "Browse Modlists" page of the Wabbajack UI get cut off.

**Additional context**
Windows 10

**Logs**
N/A, Screenshot: 
![image](https://user-images.githubusercontent.com/25124348/80781129-3f55a780-8b3f-11ea-8b72-a6f2fb92e03e.png)

**Comment by Noggog** [comment]
Cool, will take a look.   With the "pane" look, all the boxes need to be the same height on a given row.  Since I think we had a maximum text size I think I just hardcoded the height and figured it couldnt go larger due to the limit.  Maybe the limit went away, or it wasnt high enough?

Making it stretch to fit might work, but has some edge cases to worry about.

**Comment by halgari** [comment]
really old, and I don't think it's an issue anymore?
